### ISSUE TITLE
NC2500 Elemental Analyzer

### ISSUE THREAD

**Issue by jasondunken** [USEPA/lims#65]
NC2500 Elemental Analyzer (5/10/2022)

**Comment by kurtw555** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/KWOLFE/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/KWOLFE/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/KWOLFE/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




Instrument File Field Location | Universal Template File Field Location | Special Notes
-- | -- | --
Column A beginning in Row 4 | Column A (Aliquot) |  
Cell D1   Cell F1   Cell L1 | Column B (Analyte Identifier) | Cell D1 will need to be changed   from "Sample Amount" to "Amount"   Cell F1 will need to be changed   to "N Area"   Cell L1 will need to be changed   to "C Area"
Column D   Column F   Column L | Column C (Measured Value) | The Analyte Identifier (Column B   in the Universal Parser) will be in Row 4 of the specified columns. The   values in the column under the first row will need to be imported as the   Measured Value.       Ex. Values in Column D beginning   in Row 2 will need to be imported as the Measured Value for the Analyte   Identifier in Cell D4




</body>

</html>
